[package]
name = "dianthus"
authors = [ "CJ cjhillbrand@gmail.com" ]
version = "0.1.0"
description = "Dianthus application"

[dependencies]
runtime_lib = { path = "runtime_lib" }
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
rand = "0.8.4"

[workspace]
members = [
    "runtime_lib"
]