mod array_dispatcher;
mod class_dispatcher;
mod compare_dispatcher;
mod control_dispatcher;
pub mod dispatcher;
pub mod dispatcher_container;
mod double_dispatcher;
mod dup_dispatcher;
mod float_dispatcher;
mod int_dispatcher;
mod invoke_dispatcher;
mod jump_dispatcher;
mod long_dispatcher;
mod monitor_dispatcher;
mod short_dispatcher;
