on: [push]

name: Pull Request Build and Test

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PK }}
          APP_ID: ${{ secrets.APP_ID }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - name: Build Repository
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Run Linter
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ steps.get_token.outputs.app_token }}
          args: --all-features
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test