on: [push]

name: Pull Request Build and Test

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          args: --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test